### PR TITLE
Dependency updates

### PR DESCRIPTION
**Pull request by michael-o**

### CODE REVIEW

**Comment by cstamas** [comment]
@michael-o @slawekjaranowski why were all checks skipped here?

**Comment by michael-o** [comment]
Draft?

**Comment by cstamas** [comment]
Looks like some sort of interpolation failed on them, uses `inputs.ff-os` and other that looks wrong to me.

**Comment by slawekjaranowski** [comment]
- branche `dependency-updates` doesn't contain github workflow 
- branch `master` contains github workflow

GitHub Actions build are trigered on `events`.

When we have branch in the same repository which PR is created, then we have two events `pull_request` and `push` to branch and we will have duplicate builds.

In order to minimize resource consumption when PR is created from local branch builds on pull_request are skipped ... it what we see here.

There is no `push` events because branch `dependency-updates` doesn't contain github workflow.

**Pull request merged**
